/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formas;
import cashsoft.ConsultaSQL;
import java.sql.SQLException;
import cashsoft.insertarSQL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alejandra
 */
public class formaConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form formaConfiguracion
     */
    public formaConfiguracion() {
        initComponents();
        jPanelContrasenia.setVisible(false);
        jPanelUsuario.setVisible(false);
        this.setBounds(5, 5, 510, 350);
    }
    
    public void cargarDatos(String usuario) throws SQLException, ClassNotFoundException{
        
        ConsultaSQL consulta = new ConsultaSQL();
        String resultado; 
        String[] partes;
        
        resultado = consulta.realizarConsulta(usuario);
        
        partes = resultado.split(",");
        
        jLabelUsuario.setText(usuario);
        jTextIngreso.setText(partes[0]);
        jSliderAlerta.setValue(Integer.parseInt(partes[2]));
        
    }
    
    private void guardarConfiguracion() throws ClassNotFoundException{
        
        insertarSQL actualizar = new insertarSQL();
        
        String exitoso;
        
        exitoso = actualizar.actualizarRegistro(jLabelUsuario.getText(), Double.parseDouble(jTextIngreso.getText()), jSliderAlerta.getValue());
        
        jLabelMensaje.setText(exitoso);
        
        
    }
    
    private void actualizarContrasenia() throws ClassNotFoundException{
        
        insertarSQL actualizar = new insertarSQL();
        
        String exitoso;
        
        exitoso = actualizar.actualizarContrasenia(jLabelUsuario.getText(), jPasswordContraseniaActual.getText(), jPasswordContraseniaNueva.getText());
        
        jLabelMensaje.setText(exitoso);
        
        jPasswordContraseniaActual.setText("");
        jPasswordContraseniaNueva.setText("");
        jPasswordRepetirContrasenia.setText("");
        jPanelContrasenia.setVisible(false);
        this.setBounds(5, 5, 510, 350);
        
    }
    
    private void insertarUsuario() throws ClassNotFoundException{
        
        insertarSQL insertar = new insertarSQL();
        
        String exitoso;
        
        exitoso = insertar.insertarUsuario(jTextNombreUsuario.getText(), jTextContraseniaUsuario.getText(), Double.parseDouble(jTextIngresoUsuario.getText()));
        
        jLabelMensaje.setText(exitoso);
        
        jTextNombreUsuario.setText("");
        jTextContraseniaUsuario.setText("");
        jTextIngresoUsuario.setText("");
        jPanelUsuario.setVisible(false);
        this.setBounds(5, 5, 510, 350);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelIngreso = new javax.swing.JLabel();
        jTextIngreso = new javax.swing.JTextField();
        jLabelIngreso1 = new javax.swing.JLabel();
        jSliderAlerta = new javax.swing.JSlider();
        jButtonCambiarContrasenia = new javax.swing.JButton();
        jButtonCrearUsuario = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabelAlerta = new javax.swing.JLabel();
        jLabelMensaje = new javax.swing.JLabel();
        jPanelContrasenia = new javax.swing.JPanel();
        jLabelContraseniaActual = new javax.swing.JLabel();
        jLabelContraseniaNueva = new javax.swing.JLabel();
        jLabelRepetirContraseniaNueva = new javax.swing.JLabel();
        jButtonGuardarContrasenia = new javax.swing.JButton();
        jPasswordContraseniaActual = new javax.swing.JPasswordField();
        jPasswordContraseniaNueva = new javax.swing.JPasswordField();
        jPasswordRepetirContrasenia = new javax.swing.JPasswordField();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jLabelContraseniaUsuario = new javax.swing.JLabel();
        jTextContraseniaUsuario = new javax.swing.JTextField();
        jLabelIngresoUsuario = new javax.swing.JLabel();
        jTextIngresoUsuario = new javax.swing.JTextField();
        jButtonGuardarUsuario = new javax.swing.JButton();

        setBounds(new java.awt.Rectangle(0, 0, 0, 300));

        jPanelTitulo.setBackground(new java.awt.Color(153, 153, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("Configuración");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(0, 0, 153));
        jLabelUsuario.setText("Usuario");
        jLabelUsuario.setToolTipText("");

        jLabelIngreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIngreso.setText("Ingreso mensual:");

        jTextIngreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelIngreso1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIngreso1.setText("Nivel alerta (%):");

        jSliderAlerta.setPaintLabels(true);
        jSliderAlerta.setValue(75);
        jSliderAlerta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAlertaStateChanged(evt);
            }
        });

        jButtonCambiarContrasenia.setText("Cambiar Contraseña");
        jButtonCambiarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContraseniaActionPerformed(evt);
            }
        });

        jButtonCrearUsuario.setText("Crear usuario");
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelAlerta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAlerta.setText("75");

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                            .addComponent(jButtonCambiarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelAlerta))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelIngreso1)
                                .addComponent(jLabelIngreso))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                    .addComponent(jTextIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(100, 100, 100))
                                .addComponent(jSliderAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIngreso)
                    .addComponent(jTextIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSliderAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIngreso1)
                    .addComponent(jLabelAlerta))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCambiarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelContrasenia.setBackground(new java.awt.Color(204, 204, 255));

        jLabelContraseniaActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContraseniaActual.setText("Contraseña actual:");

        jLabelContraseniaNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContraseniaNueva.setText("Contraseña nueva:");

        jLabelRepetirContraseniaNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRepetirContraseniaNueva.setText("Repetir contraseña nueva:");

        jButtonGuardarContrasenia.setText("Guardar");
        jButtonGuardarContrasenia.setEnabled(false);
        jButtonGuardarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarContraseniaActionPerformed(evt);
            }
        });

        jPasswordContraseniaActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPasswordContraseniaNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordContraseniaNueva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordContraseniaNuevaFocusLost(evt);
            }
        });

        jPasswordRepetirContrasenia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordRepetirContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordRepetirContraseniaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelContraseniaLayout = new javax.swing.GroupLayout(jPanelContrasenia);
        jPanelContrasenia.setLayout(jPanelContraseniaLayout);
        jPanelContraseniaLayout.setHorizontalGroup(
            jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContraseniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContraseniaNueva)
                    .addComponent(jLabelContraseniaActual)
                    .addComponent(jLabelRepetirContraseniaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordContraseniaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPasswordRepetirContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(jPasswordContraseniaNueva)))
                .addGap(21, 21, 21))
            .addGroup(jPanelContraseniaLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButtonGuardarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContraseniaLayout.setVerticalGroup(
            jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContraseniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContraseniaActual)
                    .addComponent(jPasswordContraseniaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContraseniaNueva)
                    .addComponent(jPasswordContraseniaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRepetirContraseniaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordRepetirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonGuardarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelUsuario.setBackground(new java.awt.Color(204, 204, 255));

        jLabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombreUsuario.setText("Nombre usuario:");

        jTextNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelContraseniaUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContraseniaUsuario.setText("Contraseña:");

        jTextContraseniaUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelIngresoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIngresoUsuario.setText("Ingreso mensual:");

        jTextIngresoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonGuardarUsuario.setText("Guardar");
        jButtonGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButtonGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombreUsuario)
                    .addComponent(jLabelContraseniaUsuario)
                    .addComponent(jLabelIngresoUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextContraseniaUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIngresoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreUsuario)
                    .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContraseniaUsuario)
                    .addComponent(jTextContraseniaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIngresoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIngresoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambiarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseniaActionPerformed
        // TODO add your handling code here:
        
        jPanelContrasenia.setVisible(true);
        jPanelUsuario.setVisible(false);
        this.setBounds(5,5,510,510);
        jLabelMensaje.setText("");
        
    }//GEN-LAST:event_jButtonCambiarContraseniaActionPerformed

    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed
        // TODO add your handling code here:
        jPanelUsuario.setVisible(true);
        jPanelContrasenia.setVisible(false);
        this.setBounds(5,5,510,510);
        jLabelMensaje.setText("");
        
    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        try {
            guardarConfiguracion();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jSliderAlertaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAlertaStateChanged
        // TODO add your handling code here:
        
        Integer valorSlider = jSliderAlerta.getValue();
        
        jLabelAlerta.setText(valorSlider.toString());
        
    }//GEN-LAST:event_jSliderAlertaStateChanged

    private void jButtonGuardarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarContraseniaActionPerformed
        try {
            actualizarContrasenia();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonGuardarContraseniaActionPerformed

    private void jPasswordContraseniaNuevaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordContraseniaNuevaFocusLost
        
        if (!jPasswordContraseniaNueva.getText().equals(jPasswordRepetirContrasenia.getText())){
            
            jLabelMensaje.setText("Las contraseñas no coinciden");
            jButtonGuardarContrasenia.setEnabled(false);
            
        } else {
            
            jLabelMensaje.setText("");
            jButtonGuardarContrasenia.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_jPasswordContraseniaNuevaFocusLost

    private void jPasswordRepetirContraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordRepetirContraseniaFocusLost

        if (!jPasswordContraseniaNueva.getText().equals(jPasswordRepetirContrasenia.getText())){
            
            jLabelMensaje.setText("Las contraseñas no coinciden");
            jButtonGuardarContrasenia.setEnabled(false);
            
        } else {
            
            jLabelMensaje.setText("");
            jButtonGuardarContrasenia.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_jPasswordRepetirContraseniaFocusLost

    private void jButtonGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarUsuarioActionPerformed
        try {
            insertarUsuario();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(formaConfiguracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonGuardarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formaConfiguracion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiarContrasenia;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonGuardarContrasenia;
    private javax.swing.JButton jButtonGuardarUsuario;
    private javax.swing.JLabel jLabelAlerta;
    private javax.swing.JLabel jLabelContraseniaActual;
    private javax.swing.JLabel jLabelContraseniaNueva;
    private javax.swing.JLabel jLabelContraseniaUsuario;
    private javax.swing.JLabel jLabelIngreso;
    private javax.swing.JLabel jLabelIngreso1;
    private javax.swing.JLabel jLabelIngresoUsuario;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelRepetirContraseniaNueva;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelContrasenia;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPasswordField jPasswordContraseniaActual;
    private javax.swing.JPasswordField jPasswordContraseniaNueva;
    private javax.swing.JPasswordField jPasswordRepetirContrasenia;
    private javax.swing.JSlider jSliderAlerta;
    private javax.swing.JTextField jTextContraseniaUsuario;
    private javax.swing.JTextField jTextIngreso;
    private javax.swing.JTextField jTextIngresoUsuario;
    private javax.swing.JTextField jTextNombreUsuario;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

}
